/**
 * ETS Pro-Informatique — Télé-déclarations & attestations à Bafoussam.
 * Page métier : aide administrative de proximité, avec rôles explicitement séparés des services officiels.
 */
import { Link } from "wouter";
import { ArrowRight, BadgeCheck, FileCheck2, Files, Printer, ScanLine, ShieldCheck } from "lucide-react";
import { PageShell } from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import QuoteForm from "@/components/QuoteForm";
import Seo from "@/components/Seo";

const services = [
  { icon: FileCheck2, code: "PROC/01", title: "Télé-déclarations accompagnées", text: "Préparation et saisie de vos télé-déclarations lorsque les informations et pièces demandées sont disponibles." },
  { icon: BadgeCheck, code: "PROC/02", title: "Attestations d’immatriculation", text: "Accompagnement pour préparer une demande d’attestation d’immatriculation et rassembler les éléments à transmettre." },
  { icon: ScanLine, code: "PROC/03", title: "Numérisation & transmission", text: "Numérisation, impression et envoi des fichiers utiles à vos démarches numériques et administratives." },
];

const steps = [
  "Expliquez la démarche que vous souhaitez préparer.",
  "Rassemblez vos informations, contacts et pièces demandées par le service officiel concerné.",
  "L’équipe vous aide à saisir, préparer, numériser ou transmettre les éléments disponibles.",
  "Conservez vos références, reçus et documents générés pour suivre votre démarche.",
];

const faq = [
  { q: "Quels documents faut-il apporter ?", a: "Les pièces varient selon la télé-déclaration ou l’attestation demandée. Apportez vos documents d’identité, références, coordonnées et toute pièce indiquée par le service officiel concerné." },
  { q: "ETS Pro-Informatique délivre-t-il les attestations ?", a: "Non. ETS Pro-Informatique accompagne la préparation, la saisie, la numérisation, l’impression et la transmission. La validation et l’émission restent du ressort de l’administration ou du service officiel compétent." },
  { q: "Puis-je contacter le service avant de passer ?", a: "Oui. Écrivez sur WhatsApp ou téléphonez pour présenter votre besoin. Selon les documents et la démarche, un passage au Cybercafé Au Débit by Pro peut être nécessaire." },
];

export default function Formalities() {
  return <PageShell>
    <Seo title="Télé-déclarations & attestations à Bafoussam | ETS Pro-Informatique" description="Télé-déclarations, accompagnement pour attestations d’immatriculation, numérisation et impression de documents à Bafoussam. Services intégrés d’ETS Pro-Informatique." path="/teledeclarations-attestations-bafoussam" serviceName="Télé-déclarations et attestations à Bafoussam" serviceDescription="Accompagnement numérique pour télé-déclarations, demandes d’attestation d’immatriculation, numérisation, impression et transmission de documents à Bafoussam." />
    <PageHero eyebrow="Télé-déclarations à Bafoussam" title={<>Vos démarches numériques, <span className="text-cyan-700">mieux préparées.</span></>} description="ETS Pro-Informatique et son Cybercafé Au Débit by Pro vous accompagnent pour les télé-déclarations, attestations d’immatriculation, numérisations et documents utiles." image="/images/cybercafe-service-desk.jpg">
      <div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="formalities-action inline-flex items-center gap-2 bg-[#68B62A] px-6 py-4 text-sm font-extrabold text-white transition hover:bg-[#579c20]">Préparer ma demande <ArrowRight className="h-4 w-4" /></Link><Link href="/cybercafe-au-debit" className="formalities-secondary inline-flex items-center gap-2 border border-slate-300 bg-white px-6 py-4 text-sm font-extrabold text-slate-800 transition hover:border-cyan-700">Le Cybercafé Au Débit by Pro</Link></div>
    </PageHero>
    <section className="relative overflow-hidden bg-[#f7f6f1] py-24 sm:py-32"><div aria-hidden className="section-production-rail" /><div className="relative mx-auto max-w-7xl px-4 sm:px-8"><div className="mb-12 max-w-2xl"><span className="fabrication-tag">Formalités / Bafoussam</span><h2 className="mt-6 font-display text-4xl font-bold leading-[0.98] tracking-[-0.06em] text-slate-950 sm:text-5xl">Une assistance pratique pour passer de l’information au document préparé.</h2></div><div className="grid gap-5 lg:grid-cols-3">{services.map((service, index) => { const Icon = service.icon; return <article key={service.title} className={`service-ticket formalities-ticket print-sheet relative overflow-hidden border border-slate-200 bg-white p-7 shadow-sm ${index === 1 ? "lg:translate-y-8" : ""}`}><div className="absolute right-0 top-0 h-2 w-24 production-ribbon" /><div className="flex items-start justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[0.16em] text-cyan-700">{service.code}</p><p className="mt-2 text-[9px] font-extrabold uppercase tracking-[0.16em] text-slate-500">Dossier de service</p></div><span className="grid h-12 w-12 place-items-center bg-cyan-700 text-white"><Icon className="h-5 w-5" /></span></div><h3 className="mt-9 font-display text-2xl font-bold leading-[0.98] tracking-[-0.05em] text-slate-950">{service.title}</h3><p className="mt-4 text-sm leading-6 text-slate-600">{service.text}</p></article>; })}</div></div></section>
    <section className="bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div className="print-sheet ribbon-frame overflow-hidden bg-white/5 p-3"><img src="/images/formalities-desk.jpg" alt="Poste administratif avec documents, scanner et ordinateur" className="aspect-[1.08/1] w-full object-cover" /><div className="p-6 sm:p-7"><Files className="h-7 w-7 text-[#9ada62]" /><p className="mt-6 text-[9px] font-extrabold uppercase tracking-[0.16em] text-cyan-200">Dossier / prêt à traiter</p><h2 className="mt-3 font-display text-3xl font-bold leading-[0.98] tracking-[-0.06em]">Avant de passer au service.</h2><p className="mt-4 text-sm leading-6 text-slate-300">Réunissez vos informations et les pièces indiquées pour votre démarche. Cela aide à préparer le dossier plus efficacement.</p></div></div><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#9ada62]">Votre démarche en quatre repères</p><h2 className="mt-5 font-display text-4xl font-bold leading-[0.98] tracking-[-0.06em] sm:text-5xl">Une assistance claire, sans confusion sur les rôles.</h2><ol className="mt-10 space-y-5">{steps.map((step, index) => <li key={step} className="flex gap-5 border-t border-white/15 pt-5"><span className="font-display text-2xl font-bold text-[#9ada62]">0{index + 1}</span><p className="pt-1 text-sm leading-6 text-slate-300">{step}</p></li>)}</ol></div></div></section>
    <section className="bg-white py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-8 lg:grid-cols-[0.85fr_1.15fr]"><div className="print-sheet ribbon-frame bg-[#e8f7fa] p-8 sm:p-10"><ShieldCheck className="h-8 w-8 text-cyan-700" /><p className="mt-10 text-[10px] font-extrabold uppercase tracking-[0.16em] text-cyan-700">Un cadre transparent</p><h2 className="mt-4 font-display text-4xl font-bold leading-[0.98] tracking-[-0.06em] text-slate-950">L’accompagnement ne remplace pas l’administration.</h2><p className="mt-5 text-sm leading-6 text-slate-600">Nous vous aidons à préparer, saisir, numériser, imprimer ou transmettre les éléments disponibles. Les critères, validations et documents officiels restent de la responsabilité du service compétent.</p></div><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-cyan-700">Questions fréquentes</p><h2 className="mt-5 font-display text-4xl font-bold leading-[0.98] tracking-[-0.06em] text-slate-950">Télé-déclarations & attestations : l’essentiel.</h2><div className="mt-8 space-y-3">{faq.map((item, index) => <details key={item.q} className="formalities-faq print-sheet border border-slate-200 bg-[#f7f6f1] p-5"><summary className="cursor-pointer list-none pr-8 font-display text-xl font-bold tracking-[-0.04em] text-slate-950"><span className="mr-3 text-[10px] font-extrabold tracking-[0.16em] text-[#68B62A]">FAQ/{String(index + 1).padStart(2, "0")}</span>{item.q}</summary><p className="mt-4 border-l-2 border-cyan-700 pl-4 text-sm leading-6 text-slate-600">{item.a}</p></details>)}</div></div></div></section>
    <section className="bg-cyan-800 py-24"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div className="text-white"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#b8ea88]">Votre demande d’assistance</p><h2 className="mt-5 font-display text-4xl font-bold leading-[0.98] tracking-[-0.06em]">Dites-nous quelle démarche vous préparez.</h2><p className="mt-5 text-sm leading-6 text-cyan-50">Passez à ETS Pro-Informatique, à la descente Akwa de Bafoussam. Le Cybercafé Au Débit by Pro fait partie de nos services intégrés.</p><div className="mt-8 flex items-center gap-3 text-sm font-bold text-white"><Printer className="h-5 w-5 text-[#b8ea88]" /> Lun–Ven 07:30–18:00 · Sam 08:00–14:00</div></div><QuoteForm accent="dark" /></div></section>
  </PageShell>;
}
