/**
 * ETS Pro-Informatique — Accueil catalogue.
 * Structure : héros commercial, familles de services, sélection et conversion WhatsApp sans prix fixe.
 */
import { Link } from "wouter";
import { ArrowRight, CheckCircle2, ChevronRight, FileCheck2, Headphones, ImagePlus, LayoutPanelTop, MapPin, MessageCircle, MonitorCog, Palette, Printer, ScanLine, Shirt, ShieldCheck, Truck } from "lucide-react";
import { PageShell, quoteLink } from "@/components/SiteShell";

const categories = [
  { title: "Impression", text: "Documents, flyers, cartes et supports utiles.", icon: Printer, image: "/manus-storage/ets-pro-gallery-stationery_7ef8d754.jpg", href: "/impression-bafoussam" },
  { title: "Grand format", text: "Affiches, banderoles, roll-up et visibilité.", icon: LayoutPanelTop, image: "/manus-storage/ets-pro-gallery-grand-format_b31bb5a2.jpg", href: "/impression-bafoussam" },
  { title: "Personnalisation", text: "Textiles, tasses et objets à votre image.", icon: Shirt, image: "/manus-storage/ets-pro-gallery-serigraphie_e0d8472e.jpg", href: "/serigraphie-bafoussam" },
  { title: "Graphisme", text: "Mise en page et fichiers prêts à produire.", icon: Palette, image: "/manus-storage/ets-pro-design-works_ccfd28a9.jpg", href: "/services" },
  { title: "Photo", text: "Agrandissements, impressions et encadrements.", icon: ImagePlus, image: "/manus-storage/ets-pro-gallery-photo_6e7cc566.jpg", href: "/services" },
  { title: "Formalités", text: "Télé-déclarations et documents numériques.", icon: FileCheck2, image: "/manus-storage/ets-pro-formalities-desk_7c260fd9.jpg", href: "/teledeclarations-attestations-bafoussam" },
];

const selections = [
  { category: "Impression numérique", title: "Supports de communication", text: "Flyers, cartes de visite, invitations et documents professionnels.", image: "/manus-storage/ets-pro-gallery-stationery_7ef8d754.jpg", href: "/impression-bafoussam" },
  { category: "Sérigraphie", title: "Textile & objets personnalisés", text: "T-shirts, casquettes, tasses, gourdes et cadeaux d’entreprise.", image: "/manus-storage/ets-pro-personalisation_b445858a.jpg", href: "/serigraphie-bafoussam" },
  { category: "Cyber Au Débit", title: "Aide numérique & bureautique", text: "Saisie, scan, impression et accompagnement informatique au même endroit.", image: "/manus-storage/ets-pro-cybercafe-service-desk_d6da4692.jpg", href: "/cybercafe-au-debit" },
  { category: "Documents", title: "Formalités et attestations", text: "Un accompagnement clair pour préparer vos démarches et dossiers.", image: "/manus-storage/ets-pro-formalities-desk_7c260fd9.jpg", href: "/teledeclarations-attestations-bafoussam" },
];

export default function Home() {
  return <PageShell>
    <section className="border-b border-slate-200 bg-white">
      <div className="catalog-wrap grid gap-8 py-9 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:py-12">
        <div className="max-w-xl">
          <p className="catalog-kicker">ETS Pro-Informatique · Bafoussam</p>
          <h1 className="mt-3 font-display text-[clamp(2.15rem,4.3vw,4.1rem)] font-extrabold leading-[1.02] tracking-[-.055em] text-[#13294c]">Tout pour <span className="text-[#075bb9]">faire avancer</span> vos projets.</h1>
          <p className="mt-5 max-w-lg text-[15px] leading-7 text-slate-600">Impression, grand format, personnalisation, graphisme, cyberservices et formalités : choisissez le bon service, puis échangez directement avec notre équipe à Bafoussam.</p>
          <div className="mt-7 flex flex-wrap gap-3"><a href={quoteLink()} target="_blank" rel="noreferrer" className="catalog-primary-button"><MessageCircle className="h-4 w-4" /> Demander un devis</a><Link href="/services" className="catalog-secondary-button">Découvrir le catalogue <ArrowRight className="h-4 w-4" /></Link></div>
          <p className="mt-4 flex items-start gap-2 text-xs leading-5 text-slate-500"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#168754]" /> Les tarifs sont discutés selon le format, la quantité et la finition, via WhatsApp ou directement à l’atelier.</p>
        </div>
        <div className="relative overflow-hidden rounded-[.45rem] bg-slate-100 shadow-[0_14px_30px_rgba(19,47,88,.14)]"><img src="/manus-storage/ets-pro-hero-print-studio_2fa49fdb.jpg" alt="Atelier d’impression ETS Pro-Informatique" className="aspect-[1.36/1] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#102e58]/72 via-transparent to-transparent" /><div className="absolute bottom-0 left-0 p-6 text-white"><p className="text-[10px] font-bold tracking-[.1em] text-sky-200">ATELIER DE PRODUCTION</p><p className="mt-2 max-w-[14rem] font-display text-2xl font-extrabold leading-tight">Le bon support, au bon moment.</p></div></div>
      </div>
    </section>

    <section className="bg-white pb-8"><div className="catalog-wrap grid gap-px overflow-hidden rounded-[.42rem] border border-slate-200 bg-slate-200 md:grid-cols-4"><div className="flex items-center gap-3 bg-white p-4"><Truck className="h-5 w-5 text-[#075bb9]" /><div><p className="text-xs font-bold text-[#1c3153]">Réponse rapide</p><p className="mt-1 text-[10px] text-slate-500">Par téléphone ou WhatsApp</p></div></div><div className="flex items-center gap-3 bg-white p-4"><LayoutPanelTop className="h-5 w-5 text-[#075bb9]" /><div><p className="text-xs font-bold text-[#1c3153]">Plusieurs formats</p><p className="mt-1 text-[10px] text-slate-500">Selon votre projet</p></div></div><div className="flex items-center gap-3 bg-white p-4"><ShieldCheck className="h-5 w-5 text-[#075bb9]" /><div><p className="text-xs font-bold text-[#1c3153]">Conseil de l’équipe</p><p className="mt-1 text-[10px] text-slate-500">Devis à discuter</p></div></div><div className="flex items-center gap-3 bg-white p-4"><Headphones className="h-5 w-5 text-[#075bb9]" /><div><p className="text-xs font-bold text-[#1c3153]">Service de proximité</p><p className="mt-1 text-[10px] text-slate-500">À la descente Akwa</p></div></div></div></section>

    <section className="catalog-section bg-[#f4f6fa]"><div className="catalog-wrap"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="catalog-kicker">Nos catégories phares</p><h2 className="catalog-section-title mt-2">Choisissez votre service.</h2></div><Link href="/services" className="inline-flex items-center gap-1 text-xs font-bold text-[#075bb9]">Voir tous les services <ChevronRight className="h-4 w-4" /></Link></div><div className="mt-8 grid gap-4 grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{categories.map((item) => { const Icon = item.icon; return <Link key={item.title} href={item.href} className="catalog-card group"><img src={item.image} alt="" className="catalog-card-image" /><div className="catalog-card-body"><div className="flex items-center justify-between"><Icon className="h-4 w-4 text-[#075bb9]" /><ChevronRight className="h-4 w-4 text-slate-400 transition group-hover:translate-x-0.5 group-hover:text-[#075bb9]" /></div><h3 className="catalog-card-title">{item.title}</h3><p className="catalog-card-copy line-clamp-2">{item.text}</p></div></Link>; })}</div></div></section>

    <section className="catalog-section bg-white"><div className="catalog-wrap grid gap-8 lg:grid-cols-[.78fr_1.22fr]"><aside className="rounded-[.42rem] bg-[#102e58] p-7 text-white"><p className="text-[10px] font-bold tracking-[.1em] text-sky-200">DEMANDE RAPIDE</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-[1.05]">Un besoin précis ?<br />Parlons-en.</h2><p className="mt-4 text-sm leading-6 text-slate-200">Donnez-nous le support, le format, la quantité et le délai. L’équipe vous répond avec une proposition adaptée.</p><a href={quoteLink()} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-[.3rem] bg-white px-4 py-3 text-xs font-bold text-[#075bb9]"><MessageCircle className="h-4 w-4" /> Discuter sur WhatsApp</a><p className="mt-7 border-t border-white/15 pt-5 text-xs leading-5 text-slate-300"><MapPin className="mr-1 inline h-3.5 w-3.5" /> BP 1313, Descente Akwa, Bafoussam</p></aside><div><p className="catalog-kicker">Sélection de services</p><h2 className="catalog-section-title mt-2">Des solutions pour le quotidien.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{selections.map((item) => <article key={item.title} className="catalog-card"><img src={item.image} alt="" className="catalog-card-image" /><div className="catalog-card-body"><p className="catalog-card-category">{item.category}</p><h3 className="catalog-card-title">{item.title}</h3><p className="catalog-card-copy">{item.text}</p><div className="catalog-card-bottom"><p className="catalog-price-note">Tarif à discuter<span>Via WhatsApp ou à l’atelier</span></p><Link href={item.href} className="catalog-icon-button" aria-label={`Découvrir ${item.title}`}><ArrowRight className="h-4 w-4" /></Link></div></div></article>)}</div></div></div></section>

    <section className="border-y border-slate-200 bg-[#eef5ff]"><div className="catalog-wrap grid gap-6 py-11 md:grid-cols-[1.05fr_.95fr] md:items-center"><div><p className="catalog-kicker">Prix et disponibilité</p><h2 className="catalog-section-title mt-2">Chaque projet mérite une proposition adaptée.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-600">Les supports, formats, quantités et finitions varient selon votre besoin. Pour recevoir une estimation fiable, contactez l’équipe sur WhatsApp ou passez directement à ETS Pro-Informatique.</p></div><div className="flex flex-wrap gap-3 md:justify-end"><a href={quoteLink()} target="_blank" rel="noreferrer" className="catalog-primary-button"><MessageCircle className="h-4 w-4" /> Demander une estimation</a><Link href="/contact" className="catalog-secondary-button"><MonitorCog className="h-4 w-4" /> Voir les contacts</Link></div></div></section>

    <section className="catalog-section bg-white"><div className="catalog-wrap grid gap-7 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="overflow-hidden rounded-[.42rem] bg-slate-100"><img src="/manus-storage/ets-pro-cybercafe-service-desk_d6da4692.jpg" alt="Service Cyber Au Débit by Pro" className="aspect-[1.35/1] w-full object-cover" /></div><div><p className="catalog-kicker">Cyber Au Débit by Pro</p><h2 className="catalog-section-title mt-2">Vos services numériques, au même endroit.</h2><p className="mt-4 text-sm leading-6 text-slate-600">Impression, scan, saisie, internet, documents et formalités numériques : le Cyber Au Débit by Pro est un service intégré d’ETS Pro-Informatique.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><p className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#168754]" /> Assistance bureautique</p><p className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#168754]" /> Impression et numérisation</p><p className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#168754]" /> Démarches en ligne</p><p className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-[#168754]" /> Devis sur WhatsApp</p></div><Link href="/cybercafe-au-debit" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#075bb9]">Découvrir le service <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </PageShell>;
}
