/** ETS Pro-Informatique — Catalogue de services filtrable, sans prix fixe. */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, FileCheck2, Frame, Heart, ImagePlus, LayoutPanelTop, MonitorCog, Palette, Printer, Shirt } from "lucide-react";
import { PageShell, quoteLink } from "@/components/SiteShell";
import PageHero from "@/components/PageHero";
import ServiceFaq from "@/components/ServiceFaq";

const services = [
  { title: "Impression numérique", category: "Impression", image: "/manus-storage/ets-pro-gallery-stationery_7ef8d754.jpg", icon: Printer, text: "Cartes, flyers, dépliants, badges et documents professionnels.", href: "/impression-bafoussam" },
  { title: "Grand format", category: "Impression", image: "/manus-storage/ets-pro-gallery-grand-format_b31bb5a2.jpg", icon: LayoutPanelTop, text: "Affiches, banderoles, roll-up et supports de visibilité.", href: "/impression-bafoussam" },
  { title: "Graphisme de production", category: "Création", image: "/manus-storage/ets-pro-design-works_ccfd28a9.jpg", icon: Palette, text: "Visuels, mises en page et fichiers prêts à produire.", href: "/contact" },
  { title: "Sérigraphie & textile", category: "Personnalisation", image: "/manus-storage/ets-pro-gallery-serigraphie_e0d8472e.jpg", icon: Shirt, text: "T-shirts, polos, casquettes et séries personnalisées.", href: "/serigraphie-bafoussam" },
  { title: "Objets personnalisés", category: "Personnalisation", image: "/manus-storage/ets-pro-personalisation_b445858a.jpg", icon: Heart, text: "Tasses, gourdes, stylos, porte-clés et cadeaux utiles.", href: "/serigraphie-bafoussam" },
  { title: "Photo & encadrement", category: "Photo", image: "/manus-storage/ets-pro-gallery-photo_6e7cc566.jpg", icon: Frame, text: "Tirages, agrandissements et supports décoratifs.", href: "/contact" },
  { title: "Cyber Au Débit by Pro", category: "Cyberservices", image: "/manus-storage/ets-pro-cybercafe-service-desk_d6da4692.jpg", icon: MonitorCog, text: "Scan, saisie, internet et accompagnement bureautique.", href: "/cybercafe-au-debit" },
  { title: "Télé-déclarations & attestations", category: "Formalités", image: "/manus-storage/ets-pro-formalities-desk_7c260fd9.jpg", icon: FileCheck2, text: "Dossiers numériques, documents et accompagnement de démarches.", href: "/teledeclarations-attestations-bafoussam" },
];

const filters = ["Tous", "Impression", "Création", "Personnalisation", "Photo", "Cyberservices", "Formalités"];

export default function Services() {
  const [active, setActive] = useState("Tous");
  const visible = useMemo(() => active === "Tous" ? services : services.filter((service) => service.category === active), [active]);
  return <PageShell>
    <PageHero eyebrow="Services ETS Pro-Informatique" title={<>Le bon service, pour <span className="text-[#075bb9]">le bon projet.</span></>} description="Parcourez notre catalogue de services. Pour un tarif ou une disponibilité, échangez avec l’équipe via WhatsApp ou directement à l’atelier." image="/manus-storage/ets-pro-atelier-production-tactile_43de1956.jpg" />
    <section className="catalog-section bg-[#f4f6fa]"><div className="catalog-wrap"><div className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="catalog-kicker">Catalogue des services</p><h2 className="catalog-section-title mt-2">Tous les services</h2><p className="catalog-section-copy mt-3">Sélectionnez une famille pour retrouver les prestations qui correspondent à votre besoin.</p></div><p className="text-xs font-semibold text-slate-500">{visible.length} service{visible.length > 1 ? "s" : ""} affiché{visible.length > 1 ? "s" : ""}</p></div><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="catalog-filter-panel h-fit"><p className="catalog-filter-label">Catégories</p><div className="mt-3">{filters.map((filter) => <button type="button" key={filter} onClick={() => setActive(filter)} className={`catalog-filter-option ${active === filter ? "is-active" : ""}`}><span className={`h-2 w-2 rounded-full ${active === filter ? "bg-[#075bb9]" : "bg-slate-300"}`} />{filter}</button>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><p className="catalog-filter-label">Besoin d’aide ?</p><p className="mt-2 text-xs leading-5 text-slate-500">Décrivez simplement votre projet à l’équipe.</p><a href={quoteLink()} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#075bb9]">Écrire sur WhatsApp <ArrowRight className="h-3.5 w-3.5" /></a></div></aside><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((service) => { const Icon = service.icon; return <article key={service.title} className="catalog-card"><Link href={service.href}><img src={service.image} alt="" className="catalog-card-image" /></Link><div className="catalog-card-body"><div className="flex items-start justify-between gap-3"><p className="catalog-card-category">{service.category}</p><button className="text-slate-400 transition hover:text-[#075bb9]" aria-label={`Ajouter ${service.title} à vos favoris`}><Heart className="h-4 w-4" /></button></div><h3 className="catalog-card-title">{service.title}</h3><p className="catalog-card-copy">{service.text}</p><div className="catalog-card-bottom"><p className="catalog-price-note">Tarif à discuter<span>Via WhatsApp ou à l’atelier</span></p><a href={quoteLink(service.title)} target="_blank" rel="noreferrer" className="catalog-icon-button" aria-label={`Demander un devis pour ${service.title}`}><ArrowRight className="h-4 w-4" /></a></div></div></article>; })}</div></div></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="catalog-wrap grid gap-5 py-9 md:grid-cols-[1fr_auto] md:items-center"><div><p className="catalog-kicker">Un projet particulier ?</p><h2 className="catalog-section-title mt-2">Parlons du format, de la quantité et du délai.</h2><p className="mt-3 text-sm leading-6 text-slate-600">L’équipe vous donnera une proposition adaptée à votre besoin. Les prix se discutent avant toute production, sur WhatsApp ou directement à Bafoussam.</p></div><a href={quoteLink()} target="_blank" rel="noreferrer" className="catalog-primary-button"><ImagePlus className="h-4 w-4" /> Demander un devis</a></div></section>
    <ServiceFaq title="Questions fréquentes sur le catalogue." intro="Les options de format, quantité, matériau et finition déterminent la proposition de l’atelier." items={[{ question: "Où puis-je voir les prix ?", answer: "Les tarifs sont discutés avec l’équipe car ils dépendent du format, de la quantité, de la finition et du délai. Écrivez sur WhatsApp ou passez à l’atelier pour une estimation." }, { question: "Puis-je demander un service qui n’est pas dans le catalogue ?", answer: "Oui. Décrivez votre besoin ; l’équipe vous orientera vers le support ou le service le plus adapté." }, { question: "Comment envoyer mon fichier ?", answer: "Vous pouvez l’envoyer par WhatsApp ou venir avec votre fichier à ETS Pro-Informatique. Indiquez toujours le format final souhaité." }]} />
  </PageShell>;
}
